require: rubocop-performance

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Lint/MixinUsage:
  Exclude:
    - 'bin/*'

Metrics/LineLength:
  Max: 154

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 130

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/*'

Metrics/AbcSize:
  Max: 20

AllCops:
  TargetRubyVersion: 2.6.3
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
